version: '3'

services:
  webapp:
    build:
      context: .     # The path to your Dockerfile (current directory in this case)
      dockerfile: Dockerfile  # Specify the Dockerfile to use (optional if using default name)
    volumes:
      - ./dockerlab/webapp/database:/app/database
    ports:
      - "3001:3000"  # Map host port 3001 to container port 3000
    restart: always   # Automatically restart the container if it stops
